[build]
  publish = "public"
  command = "bash build.sh"

[build.environment]
  HUGO_VERSION = "0.146.0"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404 