[build]
  publish = "public"
  command = "hugo --gc --minify"

[build.environment]
  HUGO_VERSION = "0.146.0"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "false"

[[redirects]]
  from = "/*"
  to = "/404.html"
  status = 404 